
version: 2.1


orbs:
  macos: circleci/macos@2.3.3
  ruby: circleci/ruby@2.0.0
  aws-cli: circleci/aws-cli@3.1.4

default-executor: &default-executor
  macos:
    xcode: 14.1.0
  working_directory: ~/circle-ci
  environment:
    FL_OUTPUT_DIR: output

jobs:
  build-test-ios:
    <<: *default-executor

    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Unit tests
          command: bundle exec fastlane ios tests
      - run:
          name: Integration tests
          command: bundle exec fastlane ios integration_tests

  build-test-macos:
    <<: *default-executor

    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Unit tests
          command: bundle exec fastlane mac tests

  build-test-tvos:
    <<: *default-executor

    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Unit tests
          command: bundle exec fastlane tvos tests

  build-test-watchos:
    <<: *default-executor

    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Unit tests
          command: bundle exec fastlane watchos tests

  release:
    <<: *default-executor

    steps:
      - add_ssh_keys:
          fingerprints:
            - "1d:f2:37:1e:7e:38:02:e0:76:2d:6a:a8:47:2e:85:09"
      - checkout
      - ruby/install-deps
      - aws-cli/setup:
          role-arn: $AWS_OIDC_ROLE_ARN
          role-session-name: "${CIRCLE_WORKFLOW_JOB_ID}.release"
          session-duration: '900'
      - run:
          name: Publish new version to cocoapods trunk
          command: bundle exec fastlane ios release

  publish-doc:
    <<: *default-executor

    steps:
      - add_ssh_keys:
          fingerprints:
            - "1d:f2:37:1e:7e:38:02:e0:76:2d:6a:a8:47:2e:85:09"
      - checkout
      - ruby/install-deps
      - run:
          name: Publish documention for new version
          command: bundle exec fastlane ios publish_doc


workflows:
  build-test-deploy:
    jobs:
      - build-test-ios
      - build-test-macos
      - build-test-tvos
      - build-test-watchos
      - release:
          filters:
            branches:
              only: release
          requires:
            - build-test-ios
            - build-test-macos
            - build-test-tvos
            - build-test-watchos
          context: amplify-swift-aws-oidc

      - publish-doc:
          filters:
            branches:
              only: release
          requires:
            - release
