
version: 2.1


orbs:
  macos: circleci/macos@2.3.3
  ruby: circleci/ruby@2.0.0


default-executor: &default-executor
  macos:
    xcode: 14.1.0
  working_directory: ~/circle-ci
  environment:
    FL_OUTPUT_DIR: output


jobs:
  build-test-ios:
    <<: *default-executor

    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Fastlane test
          command: bundle exec fastlane ios tests

  build-test-macos:
    <<: *default-executor

    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Fastlane test
          command: bundle exec fastlane mac tests

  release:
    <<: *default-executor

    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Publish new version to cocoapods trunk
          command: bundle exec fastlane ios release


workflows:
  build-test-deploy:
    jobs:
      - build-test-ios
      - build-test-macos
      - release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - build-test-ios
            - build-test-macos
