
platform :ios do
    before_all do
        setup_circle_ci
    end

    desc "Run all the tests on iOS"
    lane :tests do
        run_tests(
            clean: true,
            result_bundle: true,
            scheme: "AmplifyUtilsNotifications",
            package_path: ".",
            sdk: "iphonesimulator",
            device: "iPhone 14",
        )
    end

    desc "Publish to Cocoapods whenever a new version tag is created"
    lane :release do
        # publish to Cocoapods
        # pod_push(
        #     use_bundle_exec: true,
        #     path: "AmplifyUtilsNotifications.podspec",
        # )
    end
end

platform :mac do
    before_all do
        setup_circle_ci
    end

    desc "Run all the tests on macOS"
    lane :tests do
        run_tests(
            clean: true,
            result_bundle: true,
            include_simulator_logs: false,
            scheme: "AmplifyUtilsNotifications",
            package_path: ".",
            sdk: "macosx",
            destination: "platform=macOS",
        )
    end
end
