name: Build and Test
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
      contents: read

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-test-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          persist-credentials: false

      - name: Setup Ruby
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
        with:
          ruby-version: '3.2.1'
          bundler-cache: true

      - name: Run unit tests
        run: bundle exec fastlane ios tests

      - name: Generate Coverage Report
        continue-on-error: true
        run: |
          cd Build/Build/ProfileData
          cd $(ls -d */|head -n 1)
          pathCoverage=Build/Build/ProfileData/${PWD##*/}/Coverage.profdata
          cd ${{ github.workspace }}
          xcrun llvm-cov export -format="lcov" -instr-profile $pathCoverage Build/Build/Products/Debug-iphonesimulator/AmplifyUtilsNotifications.o > AmplifyUtilsNotifications-Coverage.lcov

      - name: Upload Report
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        continue-on-error: true
        with:
          flags: AmplifyUtilsNotifications

      - name: Run integration tests
        run: bundle exec fastlane ios integration_tests

  build-test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          persist-credentials: false

      - name: Setup Ruby
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
        with:
          ruby-version: '3.2.1'
          bundler-cache: true

      - name: Run unit tests
        run: bundle exec fastlane mac tests

  build-test-tvos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          persist-credentials: false

      - name: Setup Ruby
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
        with:
          ruby-version: '3.2.1'
          bundler-cache: true

      - name: Run unit tests
        run: bundle exec fastlane tvos tests

  build-test-watchos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          persist-credentials: false

      - name: Setup Ruby
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
        with:
          ruby-version: '3.2.1'
          bundler-cache: true

      - name: Run unit tests
        run: bundle exec fastlane watchos tests
